
logging:
    file: /data/local/tomcat/logs/matchingEngine.log
    config: classpath:logback.xml
    prefix: GLOG
    numberInfoChar: 1000
    numberDebugChar: 10000

project:
    name: match
    wiki: https://www.google.fr
    




server:
  port: '8483'
  
springdoc:
  swagger-ui:
    path: /doc-swagger.html
    


app:
    username: test
    password: test


---
#dev config
spring:
  profiles: dev
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/matchingengine?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: root
    initialization-mode: always
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
    
services:
  walletApi: localhost:9090/assets-api-rest/sendPayment
  
app:
    username: test
    password: test


---
#jenkins config
spring:
  profiles: jenkins

  datasource:
    username: root
    url: jdbc:mysql://192.168.1.32:3306/JENKINSmatchingengine?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: root
    initialization-mode: always
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
 
services:
  walletApi: localhost:9090/assets-api-rest/sendPayment
